In [28]:
#Code
import numpy as np

A = np.array([[0,4],[-1,3]])
B = np.array([[3,-8],[0,1]])
C = np.array([[0,1],[6,1]])

At = np.transpose(A)
Bt = np.transpose(B)
Ct = np.transpose(C)


R1 = np.transpose(np.dot(np.dot(A,B),C))
R2 = np.dot(np.dot(Ct,Bt),At)

AB = np.dot(A,B)
ABC = np.dot(AB,C)
ABCt = np.transpose(ABC)

CtBt = np.dot(Ct,Bt)
CtBtAt = np.dot(CtBt,At)

![](img/matrix_transpose_problem.jpg)




In [34]:
#Simple Solution

print('(A·B·C)^t =')

print(R1,end='\n\n')

print('C^t · B^t · A^t =')

print(R2,end='\n\n')

print('Therefore we show that (A·B·C)^t = C^t · B^t · A^t in this case.')

#print('-'*72+'\n')

(A·B·C)^t =
[[24 66]
 [ 4  8]]

C^t · B^t · A^t =
[[24 66]
 [ 4  8]]

Therefore we show that (A·B·C)^t = C^t · B^t · A^t in this case.


In [35]:
#Previous steps detailed, (A·B·C)^t
print('Let\'s show the previous steps detailed.\n')


print(f'A·B = \n{AB}\n')


print(f'(A·B)·C = \n{ABC}\n')


print(f'(A·B·C)^t = \n{ABCt}\n')

Let's show the previous steps detailed.

A·B = 
[[ 0  4]
 [-3 11]]

(A·B)·C = 
[[24  4]
 [66  8]]

(A·B·C)^t = 
[[24 66]
 [ 4  8]]



In [37]:
#Previous steps detailed, C^t · B^t · A^t
print(f'C^t = \n{Ct}\n')
print(f'B^t = \n{Bt}\n')
print(f'A^t = \n{At}\n')

print(f'C^t · B^t = \n{CtBt}\n')
print(f'C^t · B^t · A^t = \n{CtBtAt}\n')

C^t = 
[[0 6]
 [1 1]]

B^t = 
[[ 3  0]
 [-8  1]]

A^t = 
[[ 0 -1]
 [ 4  3]]

C^t · B^t = 
[[-48   6]
 [ -5   1]]

C^t · B^t · A^t = 
[[24 66]
 [ 4  8]]

